# Generated by Django 2.1.1 on 2018-11-05 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0010_auto_20181105_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='付款金额')),
                ('record', models.CharField(max_length=4, verbose_name='凭证号')),
                ('payday', models.DateField(verbose_name='付款时间')),
                ('text', models.TextField(blank=True, null=True, verbose_name='付款备注')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.Contract', verbose_name='所属合同')),
            ],
            options={
                'verbose_name': '付款记录',
                'verbose_name_plural': '付款记录',
                'ordering': ('contract', 'created'),
            },
        ),
    ]
