# Generated by Django 2.1.1 on 2018-11-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='record',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='凭证号'),
        ),
    ]
