# Generated by Django 2.1.1 on 2018-11-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20181105_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=10, max_digits=6, verbose_name='增值税率'),
            preserve_default=False,
        ),
    ]
