# Generated by Django 2.1.1 on 2018-11-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='增值税率'),
        ),
    ]
