# Generated by Django 2.1.1 on 2018-10-28 05:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='公司名称')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '公司',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=20, verbose_name='索引')),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='合同名称')),
                ('supplier', models.CharField(db_index=True, max_length=50, verbose_name='供应商名称')),
                ('sign', models.DateField(verbose_name='签订时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='初始金额')),
                ('definite_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='决算金额')),
                ('active', models.BooleanField(default=True, verbose_name='状态')),
                ('text', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('jgc', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.Company', verbose_name='公司')),
            ],
            options={
                'ordering': ('subject', 'index', 'created'),
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='印花税类型')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='印花税税率')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, verbose_name='种类代码')),
                ('name', models.CharField(max_length=20, verbose_name='种类名称')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='stamp',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.Stamp', verbose_name='印花税类型'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.Subject', verbose_name='合同类别'),
        ),
    ]
