# Generated by Django 2.1.1 on 2018-10-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='definite_amount',
            new_name='definite',
        ),
        migrations.AlterField(
            model_name='contract',
            name='jgc',
            field=models.BooleanField(default=False, verbose_name='甲供材'),
        ),
    ]
