# Generated by Django 2.1.1 on 2018-10-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20181028_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('subject', 'created'), 'verbose_name': '合同'},
        ),
        migrations.AddField(
            model_name='contract',
            name='master',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='补充合同'),
        ),
    ]
