# Generated by Django 2.1.1 on 2018-10-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20181028_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='index',
            field=models.CharField(max_length=30, verbose_name='索引'),
        ),
    ]
