# Generated by Django 2.1.1 on 2018-10-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20181028_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='index',
            field=models.CharField(max_length=50, verbose_name='索引'),
        ),
    ]
