# Generated by Django 2.1.1 on 2018-10-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20181029_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='合同名称'),
        ),
    ]
