# Generated by Django 2.1.1 on 2018-11-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_auto_20181029_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['created'], 'verbose_name': '公司', 'verbose_name_plural': '公司'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('subject', 'index', 'created'), 'verbose_name': '合同', 'verbose_name_plural': '合同'},
        ),
        migrations.AlterModelOptions(
            name='stamp',
            options={'ordering': ['created'], 'verbose_name': '印花税', 'verbose_name_plural': '印花税'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['created'], 'verbose_name': '合同种类', 'verbose_name_plural': '合同种类'},
        ),
    ]
