# Generated by Django 2.1.1 on 2018-11-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_auto_20181105_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_cost',
            field=models.BooleanField(default=True, verbose_name='是否进成本'),
        ),
    ]
