# Generated by Django 2.1.1 on 2018-11-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0011_contract_is_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='付款金额')),
                ('supplier', models.CharField(db_index=True, max_length=50, verbose_name='付款对象')),
                ('text', models.TextField(blank=True, null=True, verbose_name='付款说明')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='directcosts', to='contracts.Company', verbose_name='公司')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directcosts', to='contracts.Subject', verbose_name='类别')),
            ],
            options={
                'verbose_name': '非合同付款',
                'verbose_name_plural': '非合同付款',
                'ordering': ('subject', 'created'),
            },
        ),
        migrations.CreateModel(
            name='DirectPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='付款金额')),
                ('record', models.CharField(blank=True, max_length=4, null=True, verbose_name='凭证号')),
                ('payday', models.DateField(verbose_name='付款时间')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='增值税率')),
                ('text', models.TextField(blank=True, null=True, verbose_name='付款备注')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cost_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directpayments', to='minors.DirectCost', verbose_name='所属非合同付款记录')),
            ],
            options={
                'verbose_name': '付款记录',
                'verbose_name_plural': '付款记录',
                'ordering': ('cost_record', 'created'),
            },
        ),
        migrations.CreateModel(
            name='DirectRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='请款金额')),
                ('invoice', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='收到发票或凭证金额')),
                ('payday', models.DateField(verbose_name='请款时间')),
                ('text', models.TextField(blank=True, null=True, verbose_name='付款说明')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cost_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directreqs', to='minors.DirectCost', verbose_name='所属非合同付款记录')),
            ],
            options={
                'verbose_name': '非合同付款请款记录',
                'verbose_name_plural': '非合同付款请款记录',
                'ordering': ('cost_record', 'created'),
            },
        ),
    ]
