# Generated by Django 2.1.1 on 2018-10-29 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0009_auto_20181029_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='请款金额')),
                ('payday', models.DateField(verbose_name='请款时间')),
                ('invoice', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='收到发票金额')),
                ('text', models.TextField(blank=True, null=True, verbose_name='付款说明')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='contracts.Contract', verbose_name='所属合同')),
            ],
            options={
                'ordering': ('created', 'payday'),
            },
        ),
    ]
